// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: expressao.proto

public final class ExpressaoOuterClass {
  private ExpressaoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExpressaoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Expressao)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string operacao = 1;</code>
     */
    boolean hasOperacao();
    /**
     * <code>required string operacao = 1;</code>
     */
    java.lang.String getOperacao();
    /**
     * <code>required string operacao = 1;</code>
     */
    com.google.protobuf.ByteString
        getOperacaoBytes();

    /**
     * <code>optional .Expressao left = 2;</code>
     */
    boolean hasLeft();
    /**
     * <code>optional .Expressao left = 2;</code>
     */
    ExpressaoOuterClass.Expressao getLeft();
    /**
     * <code>optional .Expressao left = 2;</code>
     */
    ExpressaoOuterClass.ExpressaoOrBuilder getLeftOrBuilder();

    /**
     * <code>optional .Expressao right = 3;</code>
     */
    boolean hasRight();
    /**
     * <code>optional .Expressao right = 3;</code>
     */
    ExpressaoOuterClass.Expressao getRight();
    /**
     * <code>optional .Expressao right = 3;</code>
     */
    ExpressaoOuterClass.ExpressaoOrBuilder getRightOrBuilder();

    /**
     * <code>optional double o1 = 4;</code>
     */
    boolean hasO1();
    /**
     * <code>optional double o1 = 4;</code>
     */
    double getO1();

    /**
     * <code>optional double o2 = 5;</code>
     */
    boolean hasO2();
    /**
     * <code>optional double o2 = 5;</code>
     */
    double getO2();
  }
  /**
   * Protobuf type {@code Expressao}
   */
  public  static final class Expressao extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Expressao)
      ExpressaoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Expressao.newBuilder() to construct.
    private Expressao(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Expressao() {
      operacao_ = "";
      o1_ = 0D;
      o2_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Expressao(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              operacao_ = bs;
              break;
            }
            case 18: {
              ExpressaoOuterClass.Expressao.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = left_.toBuilder();
              }
              left_ = input.readMessage(ExpressaoOuterClass.Expressao.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(left_);
                left_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              ExpressaoOuterClass.Expressao.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = right_.toBuilder();
              }
              right_ = input.readMessage(ExpressaoOuterClass.Expressao.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(right_);
                right_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              o1_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              o2_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ExpressaoOuterClass.internal_static_Expressao_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ExpressaoOuterClass.internal_static_Expressao_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ExpressaoOuterClass.Expressao.class, ExpressaoOuterClass.Expressao.Builder.class);
    }

    private int bitField0_;
    public static final int OPERACAO_FIELD_NUMBER = 1;
    private volatile java.lang.Object operacao_;
    /**
     * <code>required string operacao = 1;</code>
     */
    public boolean hasOperacao() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string operacao = 1;</code>
     */
    public java.lang.String getOperacao() {
      java.lang.Object ref = operacao_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          operacao_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string operacao = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOperacaoBytes() {
      java.lang.Object ref = operacao_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operacao_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEFT_FIELD_NUMBER = 2;
    private ExpressaoOuterClass.Expressao left_;
    /**
     * <code>optional .Expressao left = 2;</code>
     */
    public boolean hasLeft() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Expressao left = 2;</code>
     */
    public ExpressaoOuterClass.Expressao getLeft() {
      return left_ == null ? ExpressaoOuterClass.Expressao.getDefaultInstance() : left_;
    }
    /**
     * <code>optional .Expressao left = 2;</code>
     */
    public ExpressaoOuterClass.ExpressaoOrBuilder getLeftOrBuilder() {
      return left_ == null ? ExpressaoOuterClass.Expressao.getDefaultInstance() : left_;
    }

    public static final int RIGHT_FIELD_NUMBER = 3;
    private ExpressaoOuterClass.Expressao right_;
    /**
     * <code>optional .Expressao right = 3;</code>
     */
    public boolean hasRight() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Expressao right = 3;</code>
     */
    public ExpressaoOuterClass.Expressao getRight() {
      return right_ == null ? ExpressaoOuterClass.Expressao.getDefaultInstance() : right_;
    }
    /**
     * <code>optional .Expressao right = 3;</code>
     */
    public ExpressaoOuterClass.ExpressaoOrBuilder getRightOrBuilder() {
      return right_ == null ? ExpressaoOuterClass.Expressao.getDefaultInstance() : right_;
    }

    public static final int O1_FIELD_NUMBER = 4;
    private double o1_;
    /**
     * <code>optional double o1 = 4;</code>
     */
    public boolean hasO1() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double o1 = 4;</code>
     */
    public double getO1() {
      return o1_;
    }

    public static final int O2_FIELD_NUMBER = 5;
    private double o2_;
    /**
     * <code>optional double o2 = 5;</code>
     */
    public boolean hasO2() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional double o2 = 5;</code>
     */
    public double getO2() {
      return o2_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOperacao()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasLeft()) {
        if (!getLeft().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasRight()) {
        if (!getRight().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, operacao_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getLeft());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getRight());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, o1_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, o2_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, operacao_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLeft());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getRight());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, o1_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, o2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ExpressaoOuterClass.Expressao)) {
        return super.equals(obj);
      }
      ExpressaoOuterClass.Expressao other = (ExpressaoOuterClass.Expressao) obj;

      boolean result = true;
      result = result && (hasOperacao() == other.hasOperacao());
      if (hasOperacao()) {
        result = result && getOperacao()
            .equals(other.getOperacao());
      }
      result = result && (hasLeft() == other.hasLeft());
      if (hasLeft()) {
        result = result && getLeft()
            .equals(other.getLeft());
      }
      result = result && (hasRight() == other.hasRight());
      if (hasRight()) {
        result = result && getRight()
            .equals(other.getRight());
      }
      result = result && (hasO1() == other.hasO1());
      if (hasO1()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getO1())
            == java.lang.Double.doubleToLongBits(
                other.getO1()));
      }
      result = result && (hasO2() == other.hasO2());
      if (hasO2()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getO2())
            == java.lang.Double.doubleToLongBits(
                other.getO2()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOperacao()) {
        hash = (37 * hash) + OPERACAO_FIELD_NUMBER;
        hash = (53 * hash) + getOperacao().hashCode();
      }
      if (hasLeft()) {
        hash = (37 * hash) + LEFT_FIELD_NUMBER;
        hash = (53 * hash) + getLeft().hashCode();
      }
      if (hasRight()) {
        hash = (37 * hash) + RIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getRight().hashCode();
      }
      if (hasO1()) {
        hash = (37 * hash) + O1_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getO1()));
      }
      if (hasO2()) {
        hash = (37 * hash) + O2_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getO2()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ExpressaoOuterClass.Expressao parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ExpressaoOuterClass.Expressao parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ExpressaoOuterClass.Expressao parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ExpressaoOuterClass.Expressao parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ExpressaoOuterClass.Expressao parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ExpressaoOuterClass.Expressao parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ExpressaoOuterClass.Expressao parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ExpressaoOuterClass.Expressao parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ExpressaoOuterClass.Expressao parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ExpressaoOuterClass.Expressao parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ExpressaoOuterClass.Expressao parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ExpressaoOuterClass.Expressao parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ExpressaoOuterClass.Expressao prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Expressao}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Expressao)
        ExpressaoOuterClass.ExpressaoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ExpressaoOuterClass.internal_static_Expressao_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ExpressaoOuterClass.internal_static_Expressao_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ExpressaoOuterClass.Expressao.class, ExpressaoOuterClass.Expressao.Builder.class);
      }

      // Construct using ExpressaoOuterClass.Expressao.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLeftFieldBuilder();
          getRightFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        operacao_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (leftBuilder_ == null) {
          left_ = null;
        } else {
          leftBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (rightBuilder_ == null) {
          right_ = null;
        } else {
          rightBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        o1_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        o2_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ExpressaoOuterClass.internal_static_Expressao_descriptor;
      }

      @java.lang.Override
      public ExpressaoOuterClass.Expressao getDefaultInstanceForType() {
        return ExpressaoOuterClass.Expressao.getDefaultInstance();
      }

      @java.lang.Override
      public ExpressaoOuterClass.Expressao build() {
        ExpressaoOuterClass.Expressao result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ExpressaoOuterClass.Expressao buildPartial() {
        ExpressaoOuterClass.Expressao result = new ExpressaoOuterClass.Expressao(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.operacao_ = operacao_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (leftBuilder_ == null) {
          result.left_ = left_;
        } else {
          result.left_ = leftBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (rightBuilder_ == null) {
          result.right_ = right_;
        } else {
          result.right_ = rightBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.o1_ = o1_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.o2_ = o2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ExpressaoOuterClass.Expressao) {
          return mergeFrom((ExpressaoOuterClass.Expressao)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ExpressaoOuterClass.Expressao other) {
        if (other == ExpressaoOuterClass.Expressao.getDefaultInstance()) return this;
        if (other.hasOperacao()) {
          bitField0_ |= 0x00000001;
          operacao_ = other.operacao_;
          onChanged();
        }
        if (other.hasLeft()) {
          mergeLeft(other.getLeft());
        }
        if (other.hasRight()) {
          mergeRight(other.getRight());
        }
        if (other.hasO1()) {
          setO1(other.getO1());
        }
        if (other.hasO2()) {
          setO2(other.getO2());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasOperacao()) {
          return false;
        }
        if (hasLeft()) {
          if (!getLeft().isInitialized()) {
            return false;
          }
        }
        if (hasRight()) {
          if (!getRight().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ExpressaoOuterClass.Expressao parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ExpressaoOuterClass.Expressao) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object operacao_ = "";
      /**
       * <code>required string operacao = 1;</code>
       */
      public boolean hasOperacao() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string operacao = 1;</code>
       */
      public java.lang.String getOperacao() {
        java.lang.Object ref = operacao_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            operacao_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string operacao = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOperacaoBytes() {
        java.lang.Object ref = operacao_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operacao_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string operacao = 1;</code>
       */
      public Builder setOperacao(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        operacao_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string operacao = 1;</code>
       */
      public Builder clearOperacao() {
        bitField0_ = (bitField0_ & ~0x00000001);
        operacao_ = getDefaultInstance().getOperacao();
        onChanged();
        return this;
      }
      /**
       * <code>required string operacao = 1;</code>
       */
      public Builder setOperacaoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        operacao_ = value;
        onChanged();
        return this;
      }

      private ExpressaoOuterClass.Expressao left_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ExpressaoOuterClass.Expressao, ExpressaoOuterClass.Expressao.Builder, ExpressaoOuterClass.ExpressaoOrBuilder> leftBuilder_;
      /**
       * <code>optional .Expressao left = 2;</code>
       */
      public boolean hasLeft() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Expressao left = 2;</code>
       */
      public ExpressaoOuterClass.Expressao getLeft() {
        if (leftBuilder_ == null) {
          return left_ == null ? ExpressaoOuterClass.Expressao.getDefaultInstance() : left_;
        } else {
          return leftBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Expressao left = 2;</code>
       */
      public Builder setLeft(ExpressaoOuterClass.Expressao value) {
        if (leftBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          left_ = value;
          onChanged();
        } else {
          leftBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Expressao left = 2;</code>
       */
      public Builder setLeft(
          ExpressaoOuterClass.Expressao.Builder builderForValue) {
        if (leftBuilder_ == null) {
          left_ = builderForValue.build();
          onChanged();
        } else {
          leftBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Expressao left = 2;</code>
       */
      public Builder mergeLeft(ExpressaoOuterClass.Expressao value) {
        if (leftBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              left_ != null &&
              left_ != ExpressaoOuterClass.Expressao.getDefaultInstance()) {
            left_ =
              ExpressaoOuterClass.Expressao.newBuilder(left_).mergeFrom(value).buildPartial();
          } else {
            left_ = value;
          }
          onChanged();
        } else {
          leftBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Expressao left = 2;</code>
       */
      public Builder clearLeft() {
        if (leftBuilder_ == null) {
          left_ = null;
          onChanged();
        } else {
          leftBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Expressao left = 2;</code>
       */
      public ExpressaoOuterClass.Expressao.Builder getLeftBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getLeftFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Expressao left = 2;</code>
       */
      public ExpressaoOuterClass.ExpressaoOrBuilder getLeftOrBuilder() {
        if (leftBuilder_ != null) {
          return leftBuilder_.getMessageOrBuilder();
        } else {
          return left_ == null ?
              ExpressaoOuterClass.Expressao.getDefaultInstance() : left_;
        }
      }
      /**
       * <code>optional .Expressao left = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ExpressaoOuterClass.Expressao, ExpressaoOuterClass.Expressao.Builder, ExpressaoOuterClass.ExpressaoOrBuilder> 
          getLeftFieldBuilder() {
        if (leftBuilder_ == null) {
          leftBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ExpressaoOuterClass.Expressao, ExpressaoOuterClass.Expressao.Builder, ExpressaoOuterClass.ExpressaoOrBuilder>(
                  getLeft(),
                  getParentForChildren(),
                  isClean());
          left_ = null;
        }
        return leftBuilder_;
      }

      private ExpressaoOuterClass.Expressao right_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ExpressaoOuterClass.Expressao, ExpressaoOuterClass.Expressao.Builder, ExpressaoOuterClass.ExpressaoOrBuilder> rightBuilder_;
      /**
       * <code>optional .Expressao right = 3;</code>
       */
      public boolean hasRight() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Expressao right = 3;</code>
       */
      public ExpressaoOuterClass.Expressao getRight() {
        if (rightBuilder_ == null) {
          return right_ == null ? ExpressaoOuterClass.Expressao.getDefaultInstance() : right_;
        } else {
          return rightBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Expressao right = 3;</code>
       */
      public Builder setRight(ExpressaoOuterClass.Expressao value) {
        if (rightBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          right_ = value;
          onChanged();
        } else {
          rightBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Expressao right = 3;</code>
       */
      public Builder setRight(
          ExpressaoOuterClass.Expressao.Builder builderForValue) {
        if (rightBuilder_ == null) {
          right_ = builderForValue.build();
          onChanged();
        } else {
          rightBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Expressao right = 3;</code>
       */
      public Builder mergeRight(ExpressaoOuterClass.Expressao value) {
        if (rightBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              right_ != null &&
              right_ != ExpressaoOuterClass.Expressao.getDefaultInstance()) {
            right_ =
              ExpressaoOuterClass.Expressao.newBuilder(right_).mergeFrom(value).buildPartial();
          } else {
            right_ = value;
          }
          onChanged();
        } else {
          rightBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Expressao right = 3;</code>
       */
      public Builder clearRight() {
        if (rightBuilder_ == null) {
          right_ = null;
          onChanged();
        } else {
          rightBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .Expressao right = 3;</code>
       */
      public ExpressaoOuterClass.Expressao.Builder getRightBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getRightFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Expressao right = 3;</code>
       */
      public ExpressaoOuterClass.ExpressaoOrBuilder getRightOrBuilder() {
        if (rightBuilder_ != null) {
          return rightBuilder_.getMessageOrBuilder();
        } else {
          return right_ == null ?
              ExpressaoOuterClass.Expressao.getDefaultInstance() : right_;
        }
      }
      /**
       * <code>optional .Expressao right = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ExpressaoOuterClass.Expressao, ExpressaoOuterClass.Expressao.Builder, ExpressaoOuterClass.ExpressaoOrBuilder> 
          getRightFieldBuilder() {
        if (rightBuilder_ == null) {
          rightBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ExpressaoOuterClass.Expressao, ExpressaoOuterClass.Expressao.Builder, ExpressaoOuterClass.ExpressaoOrBuilder>(
                  getRight(),
                  getParentForChildren(),
                  isClean());
          right_ = null;
        }
        return rightBuilder_;
      }

      private double o1_ ;
      /**
       * <code>optional double o1 = 4;</code>
       */
      public boolean hasO1() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double o1 = 4;</code>
       */
      public double getO1() {
        return o1_;
      }
      /**
       * <code>optional double o1 = 4;</code>
       */
      public Builder setO1(double value) {
        bitField0_ |= 0x00000008;
        o1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double o1 = 4;</code>
       */
      public Builder clearO1() {
        bitField0_ = (bitField0_ & ~0x00000008);
        o1_ = 0D;
        onChanged();
        return this;
      }

      private double o2_ ;
      /**
       * <code>optional double o2 = 5;</code>
       */
      public boolean hasO2() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional double o2 = 5;</code>
       */
      public double getO2() {
        return o2_;
      }
      /**
       * <code>optional double o2 = 5;</code>
       */
      public Builder setO2(double value) {
        bitField0_ |= 0x00000010;
        o2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double o2 = 5;</code>
       */
      public Builder clearO2() {
        bitField0_ = (bitField0_ & ~0x00000010);
        o2_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Expressao)
    }

    // @@protoc_insertion_point(class_scope:Expressao)
    private static final ExpressaoOuterClass.Expressao DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ExpressaoOuterClass.Expressao();
    }

    public static ExpressaoOuterClass.Expressao getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Expressao>
        PARSER = new com.google.protobuf.AbstractParser<Expressao>() {
      @java.lang.Override
      public Expressao parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Expressao(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Expressao> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Expressao> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ExpressaoOuterClass.Expressao getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Expressao_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Expressao_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017expressao.proto\"j\n\tExpressao\022\020\n\010operac" +
      "ao\030\001 \002(\t\022\030\n\004left\030\002 \001(\0132\n.Expressao\022\031\n\005ri" +
      "ght\030\003 \001(\0132\n.Expressao\022\n\n\002o1\030\004 \001(\001\022\n\n\002o2\030" +
      "\005 \001(\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Expressao_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Expressao_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Expressao_descriptor,
        new java.lang.String[] { "Operacao", "Left", "Right", "O1", "O2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
